=== arthika-m/ai-project/extra_x/external.dtd
<!ELEMENT students (student+)>

<!ELEMENT student (name, age, course)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT course (#PCDATA)>

=== arthika-m/ai-project/extra_x/external.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE students SYSTEM "external.dtd">

<students>

    <student>
        <name>Arun</name>
        <age>20</age>
        <course>B.Tech IT</course>
    </student>

    <student>
        <name>Priya</name>
        <age>21</age>
        <course>B.Tech CSE</course>
    </student>

</students>
